[mypy]
python_version = 3.10
# UI-Code ist (noch) nicht durchgängig typisiert
check_untyped_defs = False

# Bibliotheken ohne Typinformationen (kein py.typed / keine Stubs)
[mypy-customtkinter.*]
ignore_missing_imports = True

[mypy-pyzbar.*]
ignore_missing_imports = True

[mypy-reedsolo.*]
ignore_missing_imports = True

[mypy-qrcode.*]
ignore_missing_imports = True

[mypy-cv2.*]
ignore_missing_imports = True
